export { default as Home } from './Home';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Services } from './Services';
export { default as Portfolio } from './Portfolio';
export { default as Blog } from './Blog';
export { default as Login } from './Login';
export { default as Signup } from './Signup';
export { default as NotFound } from './NotFound';
